namespace: demo-app
commonLabels:
  pipeline: tekton
  deploy: anthos

resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.4/git-clone.yaml
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/kaniko/0.4/kaniko.yaml
- ./trigger/create-ingress.yaml
- ./trigger/create-webhook.yaml
- ./tekton/pipeline.yaml
