apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tekton-triggers
  namespace: demo-app
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "bookinfo.tekton-cicd-workflow.tk"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tekton-triggers
  namespace: demo-app
spec:
  hosts:
  - "bookinfo.tekton-cicd-workflow.tk"
  gateways:
  - tekton-triggers
  http:
  - route:
    - destination:
        host: el-demo-app-listener
        port:
          number: 8080
---    
