apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-example-sa
  namespace: demo-app
secrets:
  - name: regcred
  - name: webhook-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-example-sa
    namespace: demo-app
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-pipeline
  namespace: demo-app  
spec:
  params:
    - name: imageDetails
      type: string
    - name: contextDetails
      type: string
    - name: dockerfileDetails
      type: string
    - name: imageMongodb
      type: string
    - name: contextMongodb
      type: string
    - name: dockerfileMongodb
      type: string
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/gauravkr19/tekton-pipeline.git
        - name: revision
          value: master
      workspaces:
        - name: output
          workspace: git-source
    - name: build-image-details
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gauravkr19/details:latest
        - name: CONTEXT
          value: src/details
        - name: DOCKERFILE
          value: $(workspaces.source.path)/src/details/Dockerfile
      workspaces:
        - name: source
          workspace: git-source                                                            
    - name: build-image-mongodb
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gauravkr19/mongodb:latest
        - name: CONTEXT
          value: ./src/mongodb/
        - name: DOCKERFILE
          value: $(workspaces.source.path)/src/mongodb/Dockerfile
      workspaces:
        - name: source
          workspace: git-source                                                           
