apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-example-sa
  namespace: demo-app
secrets:
  - name: regcred
  - name: webhook-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-example-sa
    namespace: demo-app
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-pipeline
  namespace: demo-app  
spec:
  params:
    - name: image-registry
      default: docker.io/gauravkr19
    - name: imageDetails
      type: string      
    - name: contextDetails
      type: string
    - name: dockerfileDetails
      type: string
    - name: imageMongodb
      type: string
    - name: contextMongodb
      type: string
    - name: dockerfileMongodb
      type: string
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/gauravkr19/tekton-pipeline.git
        - name: revision
          value: master
      workspaces:
        - name: output
          workspace: git-source
    - name: build-image-details
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-registry)/details
        - name: CONTEXT
          value: src/details
        - name: DOCKERFILE
          value: $(workspaces.source.path)/src/details/Dockerfile
      workspaces:
        - name: source
          workspace: git-source                                                            
    - name: build-image-mongodb
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-registry)/mongodb
        - name: CONTEXT
          value: src/mongodb
        - name: DOCKERFILE
          value: $(workspaces.source.path)/src/mongodb/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
    - name: deploy-app
      taskRef:
        name: app-deploy-kubectl
      params:
      - name: imageURL
        value: $(params.image-registry)/details@$(tasks.build-image-details.results.IMAGE-DIGEST)
      - name: path
        value: $(workspaces.source.path)/manifests/details.yaml
      - name: yqArg
        value: "-d2"
      - name: yamlPathToImage
        value: "spec.template.spec.containers[0].image"
      workspaces:
      - name: source
        workspace: git-source
    - name: gke-deploy-app
      runAfter: [deploy-app]
      taskRef:
        name: gke-deploy
      params:
      - name: ARGS
        value:
        - run
        - --filename="$(workspaces.source.path)/manifests/details.yaml"
        - --cluster=anthos-gke
        - --location=us-east4
        - --project=bcm-pcidss-devops-gaurav
      workspaces:
      - name: source
        workspace: git-source                                                                         

