apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-service
secrets:
  - name: dockercreds
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: image-name
    - name: path-to-image-context
    - name: path-to-dockerfile
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/gauravkr19/tekton-pipiline.git
        - name: revision
          value: master
      workspaces:
        - name: output
          workspace: git-source
    - name: build-image-details
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gcr.io/kaniko-project/executor:v0.17.1
        - name: CONTEXT
          value: /workspace/source/tekton-pipiline/src/details
        - name: DOCKERFILE
          value: /workspace/source/tekton-pipiline/src/details/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image-mongodb
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gcr.io/kaniko-project/executor:v0.17.1
        - name: CONTEXT
          value: /workspace/source/tekton-pipiline/src/mongodb
        - name: DOCKERFILE
          value: /workspace/source/tekton-pipiline/src/mongodb/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image-mysql
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gcr.io/kaniko-project/executor:v0.17.1
        - name: CONTEXT
          value: /workspace/source/samples/bookinfo/src/mysql
        - name: DOCKERFILE
          value: /workspace/source/samples/bookinfo/src/mysql/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image-prodpage
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gcr.io/kaniko-project/executor:v0.17.1
        - name: CONTEXT
          value: /workspace/source/samples/bookinfo/src/productpage
        - name: DOCKERFILE
          value: /workspace/source/samples/bookinfo/src/productpage/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image-ratings
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gcr.io/kaniko-project/executor:v0.17.1
        - name: CONTEXT
          value: /workspace/source/samples/bookinfo/src/reviews/reviews-wlpcfg/
        - name: DOCKERFILE
          value: /workspace/source/samples/bookinfo/src/reviews/reviews-wlpcfg/Dockerfile
      workspaces:
        - name: source
          workspace: git-source 
    - name: build-image-reviews
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: gcr.io/kaniko-project/executor:v0.17.1
        - name: CONTEXT
          value: /workspace/source/samples/bookinfo/src/ratings
        - name: DOCKERFILE
          value: /workspace/source/samples/bookinfo/src/ratings/Dockerfile
      workspaces:
        - name: source
          workspace: git-source                                            
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-image-default
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: build-image
  timeout: 1h0m0s
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: dockerconfig
    secret:
      secretName: dockercreds            