apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: tekton-example
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: tekton-pv
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   local:
#     path: /home/cloud_user/data
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: worker1
#           operator: In
#           values:
#           - local-storage
