apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: demo-app
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: "gauravkr19org"
  - name: GitHubUser
    value: "gauravkr19"
  - name: GitHubRepo
    value: "tekton-pipeline"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: token
  - name: GitHubSecretStringKey
    value: secret
  - name: ExternalDomain
    value: bookinfo.tekton-cicd-workflow.tk
#   If you are using github enterprise, provide a value for GitHubDomain
#  - name: GitHubDomain
#    value: git.corp.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
