apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: demo-app
stringData:
  token: <REPLACE_WITH_GITHUB_TOKEN>
  secret: random-string-data

# Secret for Docker registry or GCR
# kubectl create -n demo-app secret docker-registry regcred  --docker-server=https://index.docker.io/v1/ --docker-username=<> --docker-password=<> --docker-email <>
