apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: demo-app-triggertemplate
  namespace: demo-app
spec: 
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: demo-app-pipeline-run-
        namespace: demo-app
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: kaniko-pipeline
        params:
          - name: imageDetails
            value: gauravkr19/details:latest
          - name: contextDetails
            value: ./src/details
          - name: dockerfileDetails
            value: ./src/details/Dockerfile
          - name: imageMongodb
            value: gauravkr19/mongodb:latest
          - name: contextMongodb
            value: /workspace/source/src/mongodb/
          - name: dockerfileMongodb
            value: $(workspaces.source.path)/src/mongodb/Dockerfile
          - name: imageMysql
            value: gauravkr19/mysql:latest
          - name: contextMysql
            value: /workspace/source/src/mysql
          - name: dockerfileMysql
            value: $(workspaces.source.path)/src/mysql/Dockerfile
          - name: imageProdpage
            value: gauravkr19/prodpage:latest
          - name: contextProdpage
            value: /workspace/source/src/productpage
          - name: dockerfileProdpage
            value: $(workspaces.source.path)/src/productpage/Dockerfile
          - name: imageRatings
            value: gauravkr19/ratings:latest
          - name: contextRatings
            value: /workspace/source/src/ratings
          - name: dockerfileRatings
            value: $(workspaces.source.path)/src/ratings/Dockerfile
          - name: imageReviews
            value: gauravkr19/reviews:latest
          - name: contextReviews
            value: /workspace/source/src/reviews/reviews-wlpcfg
          - name: dockerfileReviews
            value: $(workspaces.source.path)/src/reviews/reviews-wlpcfg/Dockerfile
          - name: url
            value: https://github.com/gauravkr19/tekton-pipeline.git
          - name: revision
            value: master                      
        workspaces:
        - name: git-source
          persistentVolumeClaim:
            claimName: mypvc
        - name: dockerconfig
          secret:
            secretName: regcred            
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: demo-app-pipelinebinding
  namespace: demo-app
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: demo-app
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: demo-app-listener
  namespace: demo-app
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - bindings:
      - ref: demo-app-pipelinebinding
      template:
        ref: demo-app-triggertemplate
